version: 2
jobs:
  build:
    machine: true

    # docker:
    #   - image: docker:1.13.1-git
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: test
          command: npm test

      # - setup_remote_docker
      #
      # - run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PW
      #     docker run -it codestates/c3s-dbupdate
