version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
          docker run -it codestates/c3s-dbupdate
