version: 2
jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: npm-install
          command: npm install

      - run:
          name: npm-test
          command: npm test

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
          docker run -e CIRCLE_PR_USERNAME=$CIRCLE_PR_USERNAME -e CIRCLE_PR_REPONAME=ABC -it codestates/c3s-dbupdate

      - store_test_results:
          path: ~/app
