version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1-git
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
          docker run -i -t -e (CIRCLE_PR_REPONAME CIRCLE_PR_USERNAME) codestates/c3s-circleci:0.1 /bin/bash
      - run:
          name: cd-to-main-folder
          command: cd
      - run:
          name: run-afterPR
          command: node afterPR
