version: 2
jobs:
  build:
    machine: true

    # docker:
    #   - image: docker:1.13.1-git
    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: npm-install
          command: npm install

      - run:
          name: npm-test
          command: npm test

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PW
          docker run -it codestates/c3s-dbupdate

      - store_test_results:
          path: ~/app

      - run: |
          ls
